<Project Sdk="Xpf.Sdk/1.6.0-cibuild002171">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0-windows</TargetFrameworks>
    <RootNamespace>Xamarin.PropertyEditing.Windows.Standalone</RootNamespace>
    <AssemblyName>Xamarin.PropertyEditing.Windows.Standalone</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('..\..\designer\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml') OR Exists('..\..\..\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml')">
    <DefineConstants>$(DefineConstants);USE_VS_ICONS</DefineConstants>
  </PropertyGroup>

  <Choose>
    <When Condition="Exists('..\..\designer\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml')">
      <PropertyGroup>
        <ProppyIconPath>..\..\designer\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml</ProppyIconPath>
      </PropertyGroup>
    </When>
    <When Condition="Exists('..\..\..\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml')">
      <PropertyGroup>
        <ProppyIconPath>..\..\..\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\Resources\ProppyIcons.xaml</ProppyIconPath>
      </PropertyGroup>
    </When>
  </Choose>

  <!-- Conditionally include resource file with icons when the file exists -->
  <ItemGroup Condition="Exists($(ProppyIconPath))">
    <Page Include="$(ProppyIconPath)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xamarin.PropertyEditing.Tests\Xamarin.PropertyEditing.Tests.csproj" />
    <ProjectReference Include="..\Xamarin.PropertyEditing.Windows\Xamarin.PropertyEditing.Windows.csproj" />
    <ProjectReference Include="..\Xamarin.PropertyEditing\Xamarin.PropertyEditing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="AvaloniaUI.Xpf.LicenseKey"
      Value="$(XpfLicenseKey)" />
  </ItemGroup>

</Project>